### ISSUE TITLE
Use one standard for the language

### ISSUE THREAD

**Issue by rgaiacs** [sdruskat/citation-file-format#3]
Specify how the language should be informed.

**Comment by sdruskat** [comment]
Thanks @rgaiacs !

It's easy enough to do for natural languages, so I'd suggest using [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) (3 chars, aiming to cover all natural languages), with [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) (2 chars, aiming at covering all macrolanguages) as fallback. As these differ in length it will be very easy to implement the parse.

`languages`, however, is meant to also be able to record programming languages, and I don't think there is an ISO or similar for programming languages yet? I could type up a list from, e.g., the Wikipedia list of programming languages for starters, and add an `other` typed value which could take an argument, e.g. `other=fancyNewLang`?

**Comment by rgaiacs** [comment]
@sdruskat can we use `programming-language` instead of `language`? And can we enforce that the name of the language be all lowercase without any version? This is to avoid people use `Python`, `python`, `python3`, `python3.4`, `python 3`, `python 3.4`, ...

**Comment by sdruskat** [comment]
Yes, sure. Have been thinking about introducing this key anyway. It'll be plural - `programming-languages` - to reflect collection type.

Lower case: absolutely! This can be enforced via the validation (future work, possibly in form of a PyKwalify schema).

Version-free: yes. I'm not keen on discussions whether Python 2 and Python 3 are different languages at this point.

**Comment by sdruskat** [comment]
Still to do:

- Add support for natural language ISO codes.
